services:
  webapp:
    build:
      context: ..
      dockerfile: ./docker/webapp.dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./webapp.env
    networks:
      - tp_docker_network

  api:
    build:
      context: ..
      dockerfile: ./docker/api.dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./api.env
    depends_on:
      - db
    networks:
      - tp_docker_network

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - tp_docker_network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - tp_docker_network

volumes:
  postgres_data:

networks:
  tp_docker_network:
